spring:
  application:
    name: springServerApi
  datasource:
    url: jdbc:mysql://localhost:3306/springdata_mybatis?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8082
  servlet:
    context-path: "/api-v1"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
