server:
  port: 8080
  servlet:
    context-path: /api-v1
## 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_admin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

