server:
  port: 8088
  servlet:
    context-path: /api-v1
## 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_admin?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
