spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8088
  servlet:
    context-path: "/api-v1"

mybatis:
  #  type-aliases-package: com.zero.serverApi.entity
  mapper-locations: mybatis/mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


jwt:
  token:
    expire:
      time: 30